PROMPT Table EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE"
CREATE TABLE EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE"
(
    SALE_DATE        DATE,
    REGION           VARCHAR2(50 BYTE),
    AMOUNT           NUMBER,
    "Col_lowercase"  VARCHAR2(10 BYTE) DEFAULT 'test' NOT NULL
)
NOCOMPRESS
TABLESPACE EXTORA_APP_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            )
PARTITION BY RANGE (SALE_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
  PARTITION SALES_DATA_INITIAL VALUES LESS THAN (TO_DATE(' 2022-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                ),
  PARTITION VALUES LESS THAN (TO_DATE(' 2022-02-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                ),
  PARTITION VALUES LESS THAN (TO_DATE(' 2022-03-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                )
)
NOCACHE
RESULT_CACHE (MODE DEFAULT);


COMMENT ON TABLE EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE" IS 'Comment for table t_lowercase_RANGE_PART_INTERVAL_DATE';

COMMENT ON COLUMN EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE".SALE_DATE       IS 'Column comment for SALES_DATE in t_lowercase_RANGE_PART_INTERVAL_DATE';

COMMENT ON COLUMN EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE"."Col_lowercase" IS 'Column comment for "Col_lowercase" in t_lowercase_RANGE_PART_INTERVAL_DATE';


PROMPT Index EXTORA_APP."pk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
CREATE INDEX EXTORA_APP."pk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk" ON EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE"
(SALE_DATE, REGION)
TABLESPACE EXTORA_APP_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );

PROMPT Index EXTORA_APP."uk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
CREATE INDEX EXTORA_APP."uk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk" ON EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE"
(AMOUNT)
TABLESPACE EXTORA_APP_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );


ALTER TABLE EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE" ADD (
  CONSTRAINT "ck_lowercase_T_RANGE_PART_INTERVAL_DATE"
  CHECK (amount BETWEEN 1 and 1000000 )
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE,
  CONSTRAINT "pk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
  PRIMARY KEY (SALE_DATE, REGION)
  DEFERRABLE INITIALLY DEFERRED
  USING INDEX EXTORA_APP."pk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
  ENABLE VALIDATE,
  CONSTRAINT "uk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
  UNIQUE (AMOUNT)
  DEFERRABLE INITIALLY DEFERRED
  USING INDEX EXTORA_APP."uk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
  ENABLE VALIDATE);
