CREATE TABLE EXTORA_APP.T_CACHE__ROWMOVEMENT__COLLATION
(
    ID  NUMBER
)
DEFAULT COLLATION USING_NLS_SORT_CI
TABLESPACE EXTORA_APP_DATA
PCTFREE    19
INITRANS   21
MAXTRANS   255
STORAGE    (
            MINEXTENTS       17
            MAXEXTENTS       18
            PCTINCREASE      0
            BUFFER_POOL      RECYCLE
            FLASH_CACHE      KEEP
            CELL_FLASH_CACHE KEEP
            )
NOCOMPRESS
CACHE
RESULT_CACHE (MODE FORCE)
ENABLE ROW MOVEMENT;
