DROP USER EXTORA_APP CASCADE;

CREATE USER EXTORA_APP
  IDENTIFIED BY <password>
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE EXTORA_APP_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;