CREATE TABLE EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE"
(
    SALE_DATE        DATE,
    REGION           VARCHAR2(50 BYTE),
    AMOUNT           NUMBER,
    "Col_lowercase"  VARCHAR2(10 BYTE) DEFAULT 'test' NOT NULL
)
NOCOMPRESS
TABLESPACE EXTORA_APP_DATA
NOCACHE;


CREATE INDEX EXTORA_APP."pk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk" ON EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE"
(SALE_DATE, REGION)
LOGGING
TABLESPACE EXTORA_APP_INDEX;
CREATE INDEX EXTORA_APP."uk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk" ON EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE"
(AMOUNT)
LOGGING
TABLESPACE EXTORA_APP_INDEX;

ALTER TABLE EXTORA_APP."t_lowercase_RANGE_PART_INTERVAL_DATE" ADD (
  CONSTRAINT "ck_lowercase_T_RANGE_PART_INTERVAL_DATE"
  CHECK (amount BETWEEN 1 and 1000000 )
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE,
  CONSTRAINT "pk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
  PRIMARY KEY (SALE_DATE, REGION)
  DEFERRABLE INITIALLY DEFERRED
  USING INDEX EXTORA_APP."pk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
  ENABLE VALIDATE,
  CONSTRAINT "uk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
  UNIQUE (AMOUNT)
  DEFERRABLE INITIALLY DEFERRED
  USING INDEX EXTORA_APP."uk_lowercase_T_RANGE_PART_INTERVAL_DATE_pk"
  ENABLE VALIDATE);
