CREATE TABLE EXTORA_APP.T_LIST_PART__MULTICOLUMN
(
    SALE_DATE         DATE,
    REGION            VARCHAR2(50 BYTE),
    PRODUCT_CATEGORY  VARCHAR2(50 BYTE),
    AMOUNT            NUMBER
)
NOCOMPRESS
TABLESPACE EXTORA_APP_DATA
PARTITION BY LIST (REGION, PRODUCT_CATEGORY)
(
  PARTITION NORTH_ELECTRONICS VALUES (( 'North', 'Electronics' ))
    LOGGING
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA,
  PARTITION NORTH_CLOTHING VALUES (( 'North', 'Clothing' ))
    LOGGING
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA,
  PARTITION SOUTH_ELECTRONICS VALUES (( 'South', 'Electronics' ))
    LOGGING
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA,
  PARTITION SOUTH_CLOTHING VALUES (( 'South', 'Clothing' ))
    LOGGING
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA,
  PARTITION OTHER_SALES VALUES (DEFAULT)
    LOGGING
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
)
NOCACHE;
