CREATE TABLE EXTORA_APP.T_COMPRESS_BASIC
(
    ID  NUMBER,
    V1  VARCHAR2(100 BYTE),
    V2  VARCHAR2(100 BYTE),
    V3  VARCHAR2(100 BYTE),
    V4  VARCHAR2(100 BYTE)
)
TABLESPACE EXTORA_APP_DATA
LOGGING
COMPRESS BASIC
NOCACHE;


ALTER TABLE EXTORA_APP.T_COMPRESS_BASIC ADD (
  CONSTRAINT PK_T_COMPRESS_BASIC
  PRIMARY KEY
  (ID, V1)
  DISABLE NOVALIDATE);
