CREATE TABLE EXTORA_APP.T_LIST_PART__MULTICOLUMN
(
    SALE_DATE         DATE,
    REGION            VARCHAR2(50 BYTE),
    PRODUCT_CATEGORY  VARCHAR2(50 BYTE),
    AMOUNT            NUMBER
)
NOCOMPRESS
TABLESPACE EXTORA_APP_DATA
NOCACHE;
