CREATE TABLE EXTORA_APP.T_RANGE_PART__RANGE_SUBPART
(
    ID      NUMBER,
    SUB_ID  NUMBER
)
NOCOMPRESS
TABLESPACE USERS
PARTITION BY RANGE (ID)
INTERVAL (10)
(
  PARTITION P_0 VALUES LESS THAN (0)
    NOLOGGING
    COMPRESS BASIC
    TABLESPACE EXTORA_APP_DATA
)
NOCACHE;
