CREATE USER pyddl_test IDENTIFIED BY pyddl_test;
GRANT CREATE SESSION TO pyddl_test;
GRANT CREATE TABLE TO pyddl_test;
GRANT SELECT_CATALOG_ROLE TO pyddl_test;

ALTER USER pyddl_test DEFAULT TABLESPACE users;
ALTER USER pyddl_test TEMPORARY TABLESPACE temp;
ALTER USER pyddl_test QUOTA UNLIMITED ON users;
