CREATE TABLE EXTORA_APP.SALES_SIMPLE_RANGE
(
    SALE_DATE  DATE,
    AMOUNT     NUMBER
)
NOCOMPRESS
NOCACHE
RESULT_CACHE (MODE DEFAULT);


CREATE UNIQUE INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_01 ON EXTORA_APP.SALES_SIMPLE_RANGE
(SALE_DATE)
LOGGING;
CREATE INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_LOCAL ON EXTORA_APP.SALES_SIMPLE_RANGE
(AMOUNT)
LOCAL;
CREATE INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_MONITORED ON EXTORA_APP.SALES_SIMPLE_RANGE
(SALE_DATE, AMOUNT)
LOGGING;
ALTER INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_MONITORED
  MONITORING USAGE;
