CREATE TABLE EXTORA_APP.T_COMPRESS_BASIC
(
    ID  NUMBER,
    V1  VARCHAR2(100 BYTE),
    V2  VARCHAR2(100 BYTE),
    V3  VARCHAR2(100 BYTE),
    V4  VARCHAR2(100 BYTE)
)
LOGGING
COMPRESS BASIC
NOCACHE
RESULT_CACHE (MODE DEFAULT);


ALTER TABLE EXTORA_APP.T_COMPRESS_BASIC ADD (
  CONSTRAINT CK_T_COMPRESS_BASIC
  CHECK (v2 = upper(v2))
  DISABLE NOVALIDATE,
  CONSTRAINT PK_T_COMPRESS_BASIC
  PRIMARY KEY (ID, V1)
  DISABLE NOVALIDATE,
  CONSTRAINT UK_T_COMPRESS_BASIC
  UNIQUE (V2)
  DISABLE NOVALIDATE);
