CREATE TABLE EXTORA_APP.T_LIST_PART__AUTOMATIC
(
    ID            NUMBER,
    COUNTRY_CODE  VARCHAR2(5 BYTE),
    CUSTOMER_ID   NUMBER,
    ORDER_DATE    DATE,
    ORDER_TOTAL   NUMBER(8,2)
)
NOCOMPRESS
NOCACHE
RESULT_CACHE (MODE DEFAULT);
