create table EXTORA_APP.T_STANDARD_DATATYPES
(
    C_VARCHAR2                          varchar2(10 byte),
    C_VARCHAR2_NOT_NULL                 varchar2(11 byte) not null,
    C_VARCHAR2_DEF_Y_CHAR               varchar2(12 char) default 'Y',
    C_VARCHAR2_DEF_ON_NULL_BYTE         varchar2(13 byte) default on null 'N' not null,
    C_VARCHAR2_DEF_ON_NULL_NO_DEF       varchar2(14 byte),
    C_VARCHAR2_COMMENT                  varchar2(17 byte),
    C_VARCHAR2_COLLATION                varchar2(18 byte) collate using_nls_sort_ai default 'abc' not null,
    C_VARCHAR2_VIRTUAL_CONCAT           varchar2(200 byte) generated always as ("C_VARCHAR2"||':'||"C_VARCHAR2_NOT_NULL"),
    C_NVARCHAR2                         nvarchar2(21),
    C_VARCHAR                           varchar2(21 byte),
    C_CHAR                              char(19 byte),
    C_CHAR_VARYING                      varchar2(22 byte),
    C_CHAR_NO_LENGTH                    char(1 byte),
    C_NCHAR                             nchar(22),
    C_NCHAR_VARYING                     nvarchar2(22),
    C_NCHAR_NO_LENGTH                   nchar(1),
    C_CHARACTER                         char(20 byte),
    C_CHARACTER_VARYING                 varchar2(20 byte),
    C_NATIONAL_CHAR                     nchar(22),
    C_NATIONAL_CHAR_VARYING             nvarchar2(22),
    C_NATIONAL_CHARACTER                nchar(22),
    C_NATIONAL_CHARACTER_VARYING        nvarchar2(22),
    C_NUMBER                            number,
    C_NUMBER_PRECISION_38               number(38),
    C_NUMBER_PRECISION_20               number(20),
    C_NUMBER_PRECISION_38_SCALE         number(38,3),
    C_NUMBER_PRECISION_38_SCALE_38      number(38,38),
    C_INTEGER                           integer,
    C_INT                               integer,
    C_SMALLINT                          integer,
    C_NUMBERIC                          integer,
    C_DECIMAL                           integer,
    C_DEC                               integer,
    C_NUMBERIC_PRECISION                number(20),
    C_DECIMAL_PRECISION                 number(20),
    C_DEC_PRECISION                     number(20),
    C_NUMBERIC_PRECISION_SCALE          number(20,3),
    C_DECIMAL_PRECISION_SCALE           number(20,3),
    C_DEC_PRECISION_SCALE               number(20,3) not null,
    C_DATE_DAFAULT                      date default sysdate,
    C_DATE                              date,
    C_DATE_NOT_NULL                     date not null,
    C_LONG                              long,
    C_RAW                               raw(1),
    C_ROWID                             rowid,
    C_UROWID                            urowid(4000),
    C_UROWID_40                         urowid(40),
    C_CLOB                              clob,
    C_CLOB_STORAGE                      clob,
    C_CLOB_LOB_PAR                      clob,
    C_NCLOB                             nclob,
    C_BLOB                              blob,
    C_BFILE                             bfile,
    C_FLOAT                             float(126),
    C_FLOAT_PRECISION_22                float(22),
    C_FLOAT_PRECISION_3                 float(3),
    C_DOUBLE_PRECISION                  float(126),
    C_BINARY_DOUBLE                     binary_double,
    C_BINARY_FLOAT                      binary_float,
    C_REAL                              float(63),
    C_XML                               sys.xmltype,
    C_INTERVAL_DAY_SEC                  interval day(2) to second(6),
    C_INTERVAL_DAY2_SEC6                interval day(2) to second(6),
    C_INTERVAL_DAY3_SEC9                interval day(3) to second(9),
    C_INTERVAL_YM                       interval year(2) to month,
    C_INTERVAL_YM2                      interval year(2) to month,
    C_INTERVAL_YM3                      interval year(3) to month,
    C_TIMESTAMP                         timestamp(6),
    C_TIMESTAMP6                        timestamp(6),
    C_TIMESTAMP3                        timestamp(3),
    C_TIMESTAMP_TZ                      timestamp(6) with time zone,
    C_TIMESTAMP_TZ6                     timestamp(6) with time zone,
    C_TIMESTAMP_TZ9                     timestamp(9) with time zone,
    C_TIMESTAMP_LTZ6                    timestamp(6) with local time zone,
    C_TIMESTAMP_LTZ0                    timestamp(0) with local time zone,
    C_ANYDATA                           sys.anydata,
    C_JSON                              json,
    "c_Camel_Case_Name       32 Chars"  varchar2(100 byte),
    C_VARCHAR2_NOT_VISIBLE              varchar2(16 byte) invisible,
    C_DATE_INVISIBLE                    date invisible default sysdate not null
)
tablespace EXTORA_APP_DATA
pctfree    10
initrans   1
maxtrans   255
storage    (
            pctincrease      0
            buffer_pool      DEFAULT
            )
logging
nocompress
nocache
result_cache (mode default);
