PROMPT Table EXTORA_APP.SALES_SIMPLE_RANGE
CREATE TABLE EXTORA_APP.SALES_SIMPLE_RANGE
(
    SALE_DATE  DATE NOT NULL,
    AMOUNT     NUMBER
)
NOCOMPRESS
TABLESPACE EXTORA_APP_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            )
PARTITION BY RANGE (SALE_DATE)
(
  PARTITION SALES_Q1 VALUES LESS THAN (TO_DATE(' 2022-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                ),
  PARTITION SALES_Q2 VALUES LESS THAN (TO_DATE(' 2022-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                ),
  PARTITION SALES_Q3 VALUES LESS THAN (TO_DATE(' 2022-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                ),
  PARTITION SALES_Q4 VALUES LESS THAN (TO_DATE(' 2023-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                ),
  PARTITION SALES_DATA_FUTURE VALUES LESS THAN (MAXVALUE)
    NOCOMPRESS
    TABLESPACE EXTORA_APP_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                )
)
NOCACHE
RESULT_CACHE (MODE DEFAULT);


PROMPT Index EXTORA_APP.IDX_SALES_SIMPLE_RANGE_01
CREATE UNIQUE INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_01 ON EXTORA_APP.SALES_SIMPLE_RANGE
(SALE_DATE)
TABLESPACE EXTORA_APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );

PROMPT Index EXTORA_APP.IDX_SALES_SIMPLE_RANGE_LOCAL
CREATE INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_LOCAL ON EXTORA_APP.SALES_SIMPLE_RANGE
(AMOUNT)
STORAGE    (
            BUFFER_POOL      DEFAULT
            )
LOCAL;

PROMPT Index EXTORA_APP.IDX_SALES_SIMPLE_RANGE_MONITORED
CREATE INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_MONITORED ON EXTORA_APP.SALES_SIMPLE_RANGE
(SALE_DATE, AMOUNT)
TABLESPACE EXTORA_APP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );

ALTER INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_MONITORED
  MONITORING USAGE;


PROMPT Constraints for table EXTORA_APP.SALES_SIMPLE_RANGE
ALTER TABLE EXTORA_APP.SALES_SIMPLE_RANGE ADD (
  CONSTRAINT CK_SALES_SIMPLE_RANGE
  CHECK (SALE_DATE = trunc(SALE_DATE))
  ENABLE VALIDATE,
  CONSTRAINT PK_SALES_SIMPLE_RANGE
  PRIMARY KEY (SALE_DATE)
  USING INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_01
  ENABLE VALIDATE,
  CONSTRAINT UK_SALES_SIMPLE_RANGE
  UNIQUE (SALE_DATE, AMOUNT)
  USING INDEX EXTORA_APP.IDX_SALES_SIMPLE_RANGE_MONITORED
  ENABLE VALIDATE);
