DROP TABLESPACE EXTORA_APP_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE EXTORA_APP_DATA
DATAFILE 
  '/opt/oracle/product/23c/dbhomeFree/dbs/extora_app_data_02' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
DEFAULT 
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;