CREATE TABLE EXTORA_APP.T_RANGE_PART_INTERVAL_NUMBER
(
    SALE_ID  NUMBER,
    REGION   VARCHAR2(50 BYTE),
    AMOUNT   NUMBER
)
NOCOMPRESS
PARTITION BY RANGE (SALE_ID)
INTERVAL (1000)
(
  PARTITION INITIAL_PARTITION VALUES LESS THAN (1000)
    LOGGING
    NOCOMPRESS,
  PARTITION VALUES LESS THAN (2000)
    LOGGING
    NOCOMPRESS
)
RESULT_CACHE (MODE DEFAULT);
