PROMPT Table EXTORA_APP.T_RANGE_PART__RANGE_SUBPART
CREATE TABLE EXTORA_APP.T_RANGE_PART__RANGE_SUBPART
(
    ID      NUMBER,
    SUB_ID  NUMBER
)
NOCOMPRESS
PARTITION BY RANGE (ID)
INTERVAL (10)
(
  PARTITION P_0 VALUES LESS THAN (0)
    NOLOGGING
    COMPRESS BASIC
)
RESULT_CACHE (MODE DEFAULT);
