CREATE TABLE EXTORA_APP.T_HASH_PART
(
    EMPLOYEE_ID  NUMBER,
    FIRST_NAME   VARCHAR2(50 BYTE),
    LAST_NAME    VARCHAR2(50 BYTE),
    HIRE_DATE    DATE
)
NOCOMPRESS
PARTITION BY HASH (EMPLOYEE_ID)
    PARTITIONS 4
RESULT_CACHE (MODE DEFAULT);
