CREATE TABLE EXTORA_APP.T_LIST_PART
(
    SALE_DATE  DATE,
    REGION     VARCHAR2(50 BYTE),
    AMOUNT     NUMBER
)
NOCOMPRESS
PARTITION BY LIST (REGION)
(
  PARTITION NORTH_SALES VALUES ('North')
    LOGGING
    NOCOMPRESS,
  PARTITION SOUTH_SALES VALUES ('South')
    LOGGING
    NOCOMPRESS,
  PARTITION WEST_SALES VALUES ('West')
    LOGGING
    NOCOMPRESS,
  PARTITION EAST_SALES VALUES ('East')
    LOGGING
    NOCOMPRESS,
  PARTITION OTHER_SALES VALUES (DEFAULT)
    LOGGING
    NOCOMPRESS
)
RESULT_CACHE (MODE DEFAULT);
