CREATE USER pyddl_test IDENTIFIED BY pyddl_test;
GRANT CREATE SESSION TO pyddl_test;
GRANT CREATE TABLE TO pyddl_test;
GRANT SELECT_CATALOG_ROLE TO pyddl_test;

CREATE TABLESPACE pyddl_test_data DATAFILE 'pyddl_test_data.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 100M;
CREATE TABLESPACE pyddl_test_index DATAFILE 'pyddl_test_index.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 100M;
ALTER USER pyddl_test DEFAULT TABLESPACE pyddl_test_data;
ALTER USER pyddl_test TEMPORARY TABLESPACE temp;
ALTER USER pyddl_test QUOTA UNLIMITED ON pyddl_test_data;
ALTER USER pyddl_test QUOTA UNLIMITED ON pyddl_test_index;

CREATE ROLE PYDDL_TEST_APP_ROLE;
CREATE ROLE PYDDL_TEST_READ_ROLE;
CREATE ROLE PYDDL_TEST_USER_ROLE;
CREATE ROLE "PYDDL_TEST_lowercase_Role";

CREATE USER PYDDL_TEST_USER IDENTIFIED BY pyddl_test_user;

CREATE TABLE PYDDL_TEST_USER.SALES
(
    SALE_ID      NUMBER,
    SALE_DATE    DATE,
    SALE_AMOUNT  NUMBER
);

CREATE UNIQUE INDEX PYDDL_TEST_USER.PK_SALES ON PYDDL_TEST_USER.SALES
(SALE_DATE);

ALTER TABLE PYDDL_TEST_USER.SALES ADD (
  CONSTRAINT PK_SALES
  PRIMARY KEY (SALE_DATE)
  USING INDEX PYDDL_TEST_USER.PK_SALES
  ENABLE VALIDATE);

GRANT REFERENCES ON PYDDL_TEST_USER.SALES TO pyddl_test;
