PROMPT Foreign key PYDDL_TEST.FK_SALES_SIMPLE_RANGE_DATE_AMOUNT
ALTER TABLE PYDDL_TEST.SALES_SIMPLE_RANGE ADD (
  CONSTRAINT FK_SALES_SIMPLE_RANGE_DATE_AMOUNT
  FOREIGN KEY (SALE_DATE, AMOUNT)
  REFERENCES PYDDL_TEST.SALES (SALE_DATE, SALE_AMOUNT)
  ON DELETE CASCADE
  ENABLE VALIDATE);
