PROMPT Foreign key PYDDL_TEST.FK_SALES_SIMPLE_RANGE_AMOUNT
ALTER TABLE PYDDL_TEST.SALES_SIMPLE_RANGE ADD (
  CONSTRAINT FK_SALES_SIMPLE_RANGE_AMOUNT
  FOREIGN KEY (AMOUNT)
  REFERENCES PYDDL_TEST.SALES (SALE_AMOUNT)
  ON DELETE SET NULL
  ENABLE VALIDATE);
