PROMPT Foreign key PYDDL_TEST."fk_lowercase_T_RANGE_PART_INTERVAL_DATE_amount"
ALTER TABLE PYDDL_TEST."t_lowercase_RANGE_PART_INTERVAL_DATE" ADD (
  CONSTRAINT "fk_lowercase_T_RANGE_PART_INTERVAL_DATE_amount"
  FOREIGN KEY (AMOUNT)
  REFERENCES PYDDL_TEST.SALES (SALE_AMOUNT)
  DEFERRABLE INITIALLY DEFERRED
  DISABLE NOVALIDATE);
