PROMPT Foreign key PYDDL_TEST."fk_T_RANGE_PART_INTERVAL_DATE_Col_lowercase"
ALTER TABLE PYDDL_TEST."t_lowercase_RANGE_PART_INTERVAL_DATE" ADD (
  CONSTRAINT "fk_T_RANGE_PART_INTERVAL_DATE_Col_lowercase"
  FOREIGN KEY ("Col_lowercase")
  REFERENCES PYDDL_TEST.T_STANDARD_DATATYPES ("c_Camel_Case_Name       32 Chars")
  DEFERRABLE INITIALLY DEFERRED
  DISABLE NOVALIDATE);
