PROMPT Foreign key PYDDL_TEST.FK_T_COMPRESS_FOR_OLTP_V1
ALTER TABLE PYDDL_TEST.T_COMPRESS_FOR_OLTP ADD (
  CONSTRAINT FK_T_COMPRESS_FOR_OLTP_V1
  FOREIGN KEY (V1)
  REFERENCES PYDDL_TEST.T_COMPRESS_BASIC (V2)
  DISABLE VALIDATE);
