PROMPT Foreign key PYDDL_TEST.FK_SALES_SIMPLE_RANGE_DATE
ALTER TABLE PYDDL_TEST.SALES_SIMPLE_RANGE ADD (
  CONSTRAINT FK_SALES_SIMPLE_RANGE_DATE
  FOREIGN KEY (SALE_DATE)
  REFERENCES PYDDL_TEST_USER.SALES (SALE_DATE)
  ENABLE VALIDATE);
