PROMPT Table PYDDL_TEST.T_HASH_PART
CREATE TABLE PYDDL_TEST.T_HASH_PART
(
    EMPLOYEE_ID  NUMBER,
    FIRST_NAME   VARCHAR2(50 BYTE),
    LAST_NAME    VARCHAR2(50 BYTE),
    HIRE_DATE    DATE
)
NOCOMPRESS
TABLESPACE PYDDL_TEST_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            )
PARTITION BY HASH (EMPLOYEE_ID)
    PARTITIONS 4
    STORE IN (PYDDL_TEST_DATA, PYDDL_TEST_DATA, PYDDL_TEST_DATA, PYDDL_TEST_DATA)
NOCACHE
RESULT_CACHE (MODE DEFAULT);
