PROMPT Table PYDDL_TEST.SALES
CREATE TABLE PYDDL_TEST.SALES
(
    SALE_ID      NUMBER,
    SALE_DATE    DATE,
    SALE_AMOUNT  NUMBER
)
NOCOMPRESS
TABLESPACE PYDDL_TEST_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            )
PARTITION BY RANGE (SALE_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
  PARTITION P1 VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE PYDDL_TEST_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                ),
  PARTITION P2 VALUES LESS THAN (TO_DATE(' 2020-02-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE PYDDL_TEST_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                ),
  PARTITION P3 VALUES LESS THAN (TO_DATE(' 2020-03-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE PYDDL_TEST_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                ),
  PARTITION P4 VALUES LESS THAN (TO_DATE(' 2020-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE PYDDL_TEST_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                ),
  PARTITION VALUES LESS THAN (TO_DATE(' 2020-05-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE PYDDL_TEST_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                ),
  PARTITION VALUES LESS THAN (TO_DATE(' 2020-06-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE PYDDL_TEST_DATA
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                )
)
NOCACHE
RESULT_CACHE (MODE DEFAULT);


COMMENT ON TABLE PYDDL_TEST.SALES IS 'Sales';

COMMENT ON COLUMN PYDDL_TEST.SALES.SALE_ID     IS 'Sale ID';

COMMENT ON COLUMN PYDDL_TEST.SALES.SALE_DATE   IS 'Sale Date';

COMMENT ON COLUMN PYDDL_TEST.SALES.SALE_AMOUNT IS 'Sale Ammount';


PROMPT Index PYDDL_TEST.PK_SALES
CREATE INDEX PYDDL_TEST.PK_SALES ON PYDDL_TEST.SALES
(SALE_ID)
LOGGING
TABLESPACE PYDDL_TEST_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );

PROMPT Index PYDDL_TEST.UK_SALES
CREATE INDEX PYDDL_TEST.UK_SALES ON PYDDL_TEST.SALES
(SALE_AMOUNT)
LOGGING
TABLESPACE PYDDL_TEST_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );

PROMPT Index PYDDL_TEST.UK_SALES_02
CREATE INDEX PYDDL_TEST.UK_SALES_02 ON PYDDL_TEST.SALES
(SALE_DATE, SALE_AMOUNT)
LOGGING
TABLESPACE PYDDL_TEST_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );


PROMPT Constraints for table PYDDL_TEST.SALES
ALTER TABLE PYDDL_TEST.SALES ADD (
  CONSTRAINT CK_SALES
  CHECK (sale_amount > 0)
  DEFERRABLE INITIALLY IMMEDIATE
  ENABLE VALIDATE,
  CONSTRAINT PK_SALES
  PRIMARY KEY (SALE_ID)
  DEFERRABLE INITIALLY IMMEDIATE
  USING INDEX PYDDL_TEST.PK_SALES
  ENABLE VALIDATE,
  CONSTRAINT UK_SALES
  UNIQUE (SALE_AMOUNT)
  DEFERRABLE INITIALLY IMMEDIATE
  USING INDEX PYDDL_TEST.UK_SALES
  ENABLE VALIDATE,
  CONSTRAINT UK_SALES_02
  UNIQUE (SALE_DATE, SALE_AMOUNT)
  DEFERRABLE INITIALLY IMMEDIATE
  USING INDEX PYDDL_TEST.UK_SALES_02
  ENABLE VALIDATE);


PROMPT Grants on table PYDDL_TEST.SALES to PYDDL_TEST_APP_ROLE
GRANT ALTER, DEBUG, DELETE, FLASHBACK, INSERT, ON COMMIT REFRESH, QUERY REWRITE, READ, SELECT, UPDATE ON PYDDL_TEST.SALES TO PYDDL_TEST_APP_ROLE;

PROMPT Grants on table PYDDL_TEST.SALES to PYDDL_TEST_READ_ROLE
GRANT READ ON PYDDL_TEST.SALES TO PYDDL_TEST_READ_ROLE;

PROMPT Grants on table PYDDL_TEST.SALES to PYDDL_TEST_USER
GRANT ALTER, DEBUG, FLASHBACK, ON COMMIT REFRESH, QUERY REWRITE, READ ON PYDDL_TEST.SALES TO PYDDL_TEST_USER;
GRANT DELETE, INSERT, SELECT, UPDATE ON PYDDL_TEST.SALES TO PYDDL_TEST_USER WITH GRANT OPTION;

PROMPT Grants on table PYDDL_TEST.SALES to PYDDL_TEST_USER_ROLE
GRANT SELECT ON PYDDL_TEST.SALES TO PYDDL_TEST_USER_ROLE;

PROMPT Grants on table PYDDL_TEST.SALES to "PYDDL_TEST_lowercase_Role"
GRANT DELETE, INSERT, UPDATE ON PYDDL_TEST.SALES TO "PYDDL_TEST_lowercase_Role";
