PROMPT Table PYDDL_TEST.T_CACHE__ROWMOVEMENT__COLLATION
CREATE TABLE PYDDL_TEST.T_CACHE__ROWMOVEMENT__COLLATION
(
    ID  NUMBER NOT NULL
)
TABLESPACE PYDDL_TEST_DATA
PCTFREE    19
INITRANS   21
MAXTRANS   255
STORAGE    (
            MINEXTENTS       17
            MAXEXTENTS       18
            PCTINCREASE      0
            BUFFER_POOL      RECYCLE
            FLASH_CACHE      KEEP
            CELL_FLASH_CACHE KEEP
            )
LOGGING
NOCOMPRESS
CACHE
RESULT_CACHE (MODE FORCE)
ENABLE ROW MOVEMENT;


PROMPT Index PYDDL_TEST.PK_T_CACHE__ROWMOVEMENT__COLLATION
CREATE UNIQUE INDEX PYDDL_TEST.PK_T_CACHE__ROWMOVEMENT__COLLATION ON PYDDL_TEST.T_CACHE__ROWMOVEMENT__COLLATION
(ID)
LOGGING
TABLESPACE PYDDL_TEST_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );


PROMPT Constraints for table PYDDL_TEST.T_CACHE__ROWMOVEMENT__COLLATION
ALTER TABLE PYDDL_TEST.T_CACHE__ROWMOVEMENT__COLLATION ADD (
  CONSTRAINT PK_T_CACHE__ROWMOVEMENT__COLLATION
  PRIMARY KEY (ID)
  USING INDEX PYDDL_TEST.PK_T_CACHE__ROWMOVEMENT__COLLATION
  ENABLE VALIDATE);
