PROMPT Table PYDDL_TEST.DATABASECHANGELOGLOCK
CREATE TABLE PYDDL_TEST.DATABASECHANGELOGLOCK
(
    ID           INTEGER NOT NULL,
    LOCKED       NUMBER(1) NOT NULL,
    LOCKGRANTED  TIMESTAMP(6),
    LOCKEDBY     VARCHAR2(255 BYTE)
)
TABLESPACE PYDDL_TEST_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCOMPRESS
NOCACHE
RESULT_CACHE (MODE DEFAULT);


PROMPT Index PYDDL_TEST.PK_DATABASECHANGELOGLOCK
CREATE UNIQUE INDEX PYDDL_TEST.PK_DATABASECHANGELOGLOCK ON PYDDL_TEST.DATABASECHANGELOGLOCK
(ID)
LOGGING
TABLESPACE PYDDL_TEST_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            );


PROMPT Constraints for table PYDDL_TEST.DATABASECHANGELOGLOCK
ALTER TABLE PYDDL_TEST.DATABASECHANGELOGLOCK ADD (
  CONSTRAINT PK_DATABASECHANGELOGLOCK
  PRIMARY KEY (ID)
  USING INDEX PYDDL_TEST.PK_DATABASECHANGELOGLOCK
  ENABLE VALIDATE);
