DROP USER EXTORA_APP CASCADE;

CREATE USER extora_app
  IDENTIFIED BY extora_app
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE extora_app_data
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  